GameInspectorWeb/Areas/Admin/Models/UpcomingGameViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace GameInspectorWeb.Areas.Admin.Models
{
    public class UpcomingGameViewModel
    {

        public string Title { get; set; }

        public DateTime Time { get; set; }

        public string Platform { get; set; }


        public string PhotoPath { get; set; }

        [NotMapped]
        public IFormFile Photo { get; set; }

    }
}

GameInspectorWeb/Areas/Admin/Controllers/UpcomingGameController.cs
using GameInspectorWeb.Areas.Admin.Models;
using GameInspectorWeb.Data;
using GameInspectorWeb.Utilites;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace GameInspectorWeb.Areas.Admin.Controllers
{
    public class UpcomingGameController : AdminBaseController
    {


        public UpcomingGameController(ApplicationDbContext dbContext) : base(dbContext)
        {

        }

        public IActionResult Index()
        {
            return View(_db.UpcomingGames.ToList());
        }

        [HttpGet]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost]
        public IActionResult New(UpcomingGameViewModel vm,[FromServices] IWebHostEnvironment env)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                if (vm.Photo != null && vm.Photo.Length > 0)
                {
                    fileName = vm.Photo.GenerateFileName();
                    var savePath = Path.Combine(env.WebRootPath, "img", fileName);
                    using FileStream fs = new FileStream(savePath, FileMode.Create);
                    vm.Photo.CopyTo(fs);
                }

                var upcomingGame = new UpcomingGames()
                {
                    Title = vm.Title,
                    Time = vm.Time,
                    PhotoPath = fileName,
                    Platform = vm.Platform
                };

                _db.UpcomingGames.Add(upcomingGame);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            UpcomingGames upcomingGames = _db.UpcomingGames.Find(id);

            if (upcomingGames == null)
            {
                return NotFound();
            }

            var vm = new EditUpcomingGameViewModel()
            {
                Id = upcomingGames.Id,
                Title = upcomingGames.Title,
                PhotoPath = upcomingGames.PhotoPath,
                Platform = upcomingGames.Platform,
                Time = upcomingGames.Time
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Edit(EditUpcomingGameViewModel vm,[FromServices] IWebHostEnvironment env)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                if (vm.Photo != null && vm.Photo.Length > 0)
                {
                    fileName = vm.Photo.GenerateFileName();
                    var savePath = Path.Combine(env.WebRootPath, "img", fileName);
                    using FileStream fs = new FileStream(savePath, FileMode.Create);
                    vm.Photo.CopyTo(fs);
                }

                var upcomingGames = _db.UpcomingGames.Find(vm.Id);

                upcomingGames.Title = vm.Title;
                upcomingGames.PhotoPath = fileName;
                upcomingGames.Platform = vm.Platform;
                upcomingGames.Time = vm.Time;

                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var upcomingGames = _db.UpcomingGames.Find(id);

            if (upcomingGames == null)
            {
                return NotFound();
            }

            _db.Remove(upcomingGames);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        
    }
}

GameInspectorWeb/Areas/Admin/Views/UpcomingGame/Edit.cshtml
@model EditUpcomingGameViewModel
@{ ViewData["Title"] = "Edit Upcoming Game"; }

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <div class="card card-primary">
            @*<div class="card-header">
                    <h3 class="card-title">Quick Example</h3>
                </div>*@
            <!-- /.card-header -->
            <!-- form start -->
            <form method="post" enctype="multipart/form-data">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Title">Title</label>
                        <input asp-for="Title" class="form-control" placeholder="Title" data-slugify-target="#Slug">
                        <span asp-validation-for="Title"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Platform">Platforms</label>
                        <input asp-for="Platform" class="form-control" placeholder="Platforms">
                        <span asp-validation-for="Platform"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Time">Time</label>
                        <div class="input-group date" id="upcomingTime" data-target-input="nearest">
                            <input asp-for="Time" type="text" class="form-control datetimepicker-input" data-target="#upcomingTime" />
                            <div class="input-group-append" data-target="#upcomingTime" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>
                        <span asp-validation-for="Time"></span>
                    </div>

                    <div class="form-group">
                        <label for="exampleInputFile">File input</label>
                        <div>
                            <input type="hidden" asp-for="PhotoPath" />
                            @{ string showPreview = string.IsNullOrEmpty(Model.PhotoPath) ? "display: none" : "";}

                            <img src="~/img/@Model.PhotoPath" alt="@Model.Title" height="100" style="@showPreview" class="edit-metting-photo-preview img-thumbnail mb-2" id="img-preview" />

                        </div>
                        <div class="input-group">
                            <div class="custom-file">
                                <input asp-for="Photo" class="custom-file-input" id="exampleInputFile" data-preview-image-target="#img-preview">
                                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                            </div>
                        </div>
                        <span asp-validation-for="Photo"></span>
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.card -->

@section scripts {

    <partial name="_ValidationScriptsPartial" />

    <script>
        bsCustomFileInput.init();

        var d = new Date();

        $('#upcomingTime').datetimepicker({
            icons: {
                time: 'fas fa-clock'
            },
            format: 'DD.MM.YYYY',
            defaultDate: d
        });
    </script>

}

GameInspectorWeb/Areas/Admin/Views/UpcomingGame/Index.cshtml
@using Microsoft.AspNetCore.Antiforgery
@inject IAntiforgery Antiforgery
@model List<UpcomingGames>
@{ ViewBag.Title = "Upcoming Games";
    var tokenName = Antiforgery.GetTokens(Context).FormFieldName;
    var tokenValue = Antiforgery.GetTokens(Context).RequestToken; }

<div class="card">
    @*<div class="card-header">
            <h3 class="card-title">DataTable with default features</h3>
        </div>*@
    <!-- /.card-header -->
    <div class="card-body">
        <a id="linkNew" asp-controller="UpcomingGame" asp-action="New" class="btn btn-secondary"><i class="fas fa-plus"></i>New</a>
        <table id="dataTable" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Cover Photo</th>
                    <th>Title</th>
                    <th>Time</th>
                    <th>Platform</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
    <tr>
        <td>
            <img src="~/img/@item.PhotoPath" alt="@item.Title" width="100" />
        </td>
        <td>@item.Title</td>
        <td>@item.Time.ToShortDateString()</td>
        <td>@item.Platform</td>
        <td>

            <form class="mb-2">
                <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                @*<input type="hidden" id="idEdit" value="@item.Id" name="idEdit" />*@
                @*<input class="btn btn-warning" type="submit" value="Edit" />*@
            </form>
            <form asp-action="Delete">
                <input type="hidden" id="id" value="@item.Id" name="id" />
                <input class="btn btn-danger" type="submit" value="Delete" />
            </form>
        </td>
    </tr>
}
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

GameInspectorWeb/Areas/Admin/Views/UpcomingGame/New.cshtml
@model UpcomingGameViewModel
@{
    ViewData["Title"] = "Yeni Çıkacak Oyun Ekle";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <div class="card card-primary">
            @*<div class="card-header">
                    <h3 class="card-title">Quick Example</h3>
                </div>*@
            <!-- /.card-header -->
            <!-- form start -->
            <form method="post" enctype="multipart/form-data">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Title">Title</label>
                        <input asp-for="Title" class="form-control" placeholder="Title">
                        <span asp-validation-for="Title"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Platform">Platform</label>
                        <input asp-for="Platform" class="form-control" placeholder="Platform">
                        <span asp-validation-for="Platform"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Time">Time</label>
                        <div class="input-group date" id="upcomingTime" data-target-input="nearest">
                            <input asp-for="Time" type="text" class="form-control datetimepicker-input" data-target="#upcomingTime" />
                            <div class="input-group-append" data-target="#upcomingTime" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>
                        <span asp-validation-for="Time"></span>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">File input</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input asp-for="Photo" class="custom-file-input" id="exampleInputFile">
                                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                            </div>
                        </div>
                        <span asp-validation-for="Photo"></span>
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.card -->

@section scripts {

    <partial name="_ValidationScriptsPartial" />

    <script>
        bsCustomFileInput.init();

        var d = new Date();

        $('#upcomingTime').datetimepicker({
            icons: {
                time: 'fas fa-clock'
            },
            format: 'DD.MM.YYYY',
            defaultDate: d
        });
    </script>

}