GameInspectorWeb/Areas/Admin/Controllers/EventsController.cs
using GameInspectorWeb.Areas.Admin.Models;
using GameInspectorWeb.Data;
using GameInspectorWeb.Services;
using GameInspectorWeb.Utilites;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace GameInspectorWeb.Areas.Admin.Controllers
{
    public class EventsController : AdminBaseController
    {

        public EventsController(ApplicationDbContext dbContext) : base(dbContext)
        {
            
        }

        public IActionResult Index()
        {
            return View(_db.Articles.ToList());
        }

        [HttpGet]
        public IActionResult New()
        {
            var categories = _db.Categories.ToList();
            var selectList = new List<SelectListItem>();
            categories.ForEach(x => selectList.Add(new SelectListItem(x.CategoryName,x.Id.ToString())));

            var vm = new NewArticleViewModel
            {
                Categories = selectList
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> New(NewArticleViewModel vm, [FromServices] IWebHostEnvironment env,int[] selectedCategories)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                if (vm.CoverPhoto != null && vm.CoverPhoto.Length > 0)
                {
                    fileName = vm.CoverPhoto.GenerateFileName();
                    var savePath = Path.Combine(env.WebRootPath, "img", fileName);
                    using FileStream fs = new FileStream(savePath, FileMode.Create);
                    vm.CoverPhoto.CopyTo(fs);
                }

                if (vm.ContentPhotos != null && vm.ContentPhotos.Count > 0)
                {
                    string resim = null;
                    List<string> paths = new List<string>();
                    string path = null;
                    foreach (var photo in vm.ContentPhotos)
                    {
                        path = Guid.NewGuid() + "_" + photo.FileName;
                        var savePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img");
                        var filePath = Path.Combine(savePath, path);
                        await photo.CopyToAsync(new FileStream(filePath, FileMode.Create));
                        paths.Add(path);

                    }
                    resim = string.Join(",", paths);
                    //var data = resim.Split(',');

                    var article = new Article()
                    {
                        Title = vm.Title,
                        Content = vm.Content,
                        CharacterContent = vm.CharacterContent,
                        Time = vm.Time,
                        VideoPath = vm.VideoPath,
                        CoverPhotoPath = fileName,
                        ContentPhotosPaths = resim
                    };
                    //
                    //var ArtId = _db.Articles.OrderBy(x=>x.Id).Last().Id;

                    for (int i = 0; i < selectedCategories.Length; i++)
                    {
                        var tmp = selectedCategories[i];
                        var data = _db.Categories.FirstOrDefault(x => x.Id == tmp);
                        var ArtCat = new ArticleCategory
                        {
                            ArticleId = article.Id,
                            Article = article,
                            Category = data,
                            CategoryId = data.Id
                        };
                        article.ArticleCategories.Add(ArtCat);
                    }
                    _db.Articles.Add(article);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            return View();
        }

        public IActionResult Edit(int id)
        {
            Article article = _db.Articles.Find(id);

            if (article == null)
            {
                return NotFound();
            }

            var vm = new EditArticleViewModel()
            {
                Id = article.Id,
                Title = article.Title,
                Content = article.Content,
                CharacterContent = article.CharacterContent,
                Time = DateTime.Now,
                VideoPath = article.VideoPath,
                ExistingCoverPhotoPath = article.CoverPhotoPath,
                ExistingContentPhotoPath = article.ContentPhotosPaths
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditArticleViewModel vm, [FromServices] IWebHostEnvironment env)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                if (vm.CoverPhoto != null && vm.CoverPhoto.Length > 0)
                {
                    fileName = vm.CoverPhoto.GenerateFileName();
                    var savePath = Path.Combine(env.WebRootPath, "img", fileName);
                    using FileStream fs = new FileStream(savePath, FileMode.Create);
                    await vm.CoverPhoto.CopyToAsync(fs);
                }
                string resim = null;
                List<string> paths = new List<string>();
                string path = null;
                foreach (var photo in vm.ContentPhotos)
                {
                    path = Guid.NewGuid() + "_" + photo.FileName;
                    var savePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img");
                    var filePath = Path.Combine(savePath, path);
                    await photo.CopyToAsync(new FileStream(filePath, FileMode.Create));
                    paths.Add(path);
                }
                resim = string.Join(",", paths);
                //var data = resim.Split(',');
                var article = _db.Articles.Find(vm.Id);
                article.Title = vm.Title;
                article.Content = vm.Content;
                article.CharacterContent = vm.CharacterContent;
                article.Time = DateTime.Now;
                article.VideoPath = vm.VideoPath;
                article.CoverPhotoPath = fileName;
                article.ContentPhotosPaths = resim;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View();
        }

       [HttpPost]
       [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var article = _db.Articles.Find(id);

            if (article == null)
            {
                return NotFound();
            }

            _db.Remove(article);
            _db.SaveChanges();
            return RedirectToAction("Index");
            
        }
    }
}

GameInspectorWeb/Areas/Admin/Views/Events/Edit.cshtml
@model EditArticleViewModel
@{ ViewData["Title"] = "Edit Article"; }

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <div class="card card-primary">
            @*<div class="card-header">
                    <h3 class="card-title">Quick Example</h3>
                </div>*@
            <!-- /.card-header -->
            <!-- form start -->
            <form method="post" enctype="multipart/form-data">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Title">Article Title</label>
                        <input asp-for="Title" class="form-control" placeholder="Title" data-slugify-target="#Slug">
                        <span asp-validation-for="Title"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Content">Article Content</label>
                        <textarea asp-for="Content" class="form-control" rows="15" placeholder="Article Content"></textarea>
                        <span asp-validation-for="Content"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CharacterContent">Character Content</label>
                        <textarea class="form-control" asp-for="CharacterContent" rows="15" placeholder="Character Content"></textarea>
                        <span asp-validation-for="CharacterContent"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="VideoPath">Video Path</label>
                        <input class="form-control" asp-for="VideoPath" placeholder="Video Path URL">
                        <span asp-validation-for="VideoPath"></span>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">File input</label>
                        <div>
                            <input type="hidden" asp-for="ExistingCoverPhotoPath" />
                            @{ string showPreview = string.IsNullOrEmpty(Model.ExistingCoverPhotoPath) ? "display: none" : "";}

                            <img src="~/img/@Model.ExistingCoverPhotoPath" alt="@Model.Title" height="100" style="@showPreview" class="edit-metting-photo-preview img-thumbnail mb-2" id="img-preview" />

                        </div>
                        <div class="input-group">
                            <div class="custom-file">
                                <input asp-for="CoverPhoto" class="custom-file-input" id="exampleInputFile" data-preview-image-target="#img-preview">
                                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                            </div>
                            @*<div class="input-group-append">
                    <span class="input-group-text">Upload</span>
                </div>*@
                        </div>
                        <span asp-validation-for="CoverPhoto"></span>
                    </div>
                    <div id="gallery">
                        @foreach (var item in Model.ExistingContentPhotoPath.Split(","))
                        {
                <img src="/img/@item" alt="@item" height="100" class="edit-metting-photo-preview img-thumbnail mb-2" />}
                    </div>

                    <div class="form-group gallery">
                        <label for="exampleInputFiles">Content Files input</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input asp-for="ContentPhotos" class="custom-file-input" id="exampleInputFiles" multiple>
                                <label class="custom-file-label" for="exampleInputFiles">Choose file</label>
                            </div>
                            @*<div class="input-group-append">
                    <span class="input-group-text">Upload</span>
                </div>*@
                        </div>
                        <span asp-validation-for="ContentPhotos"></span>
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.card -->

@section scripts {

    <partial name="_ValidationScriptsPartial" />
    <script>
        $(function () {
            // Multiple images preview in browser
            var imagesPreview = function (input, placeToInsertImagePreview) {

                if (input.files) {
                    var filesAmount = input.files.length;

                    for (i = 0; i < filesAmount; i++) {
                        var reader = new FileReader();
                        $("div#gallery").empty();
                        reader.onload = function (event) {
                            $($.parseHTML('<img>')).addClass("edit-metting-photo-preview img-thumbnail mb-2").attr('src', event.target.result).appendTo(placeToInsertImagePreview);
                        }

                        reader.readAsDataURL(input.files[i]);
                    }
                }
            };

            $('#exampleInputFiles').on('change', function () {
                imagesPreview(this, 'div#gallery');
            });
        });</script>

    <script>
        bsCustomFileInput.init();
    </script>

}

GameInspectorWeb/Areas/Admin/Views/Events/Index.cshtml
@using Microsoft.AspNetCore.Antiforgery
@inject IAntiforgery Antiforgery
@model List<Article>
@{ ViewBag.Title = "Articles";
    var tokenName = Antiforgery.GetTokens(Context).FormFieldName;
    var tokenValue = Antiforgery.GetTokens(Context).RequestToken; }

<div class="card">
    @*<div class="card-header">
            <h3 class="card-title">DataTable with default features</h3>
        </div>*@
    <!-- /.card-header -->
    <div class="card-body">
        <a id="linkNew" asp-controller="Events" asp-action="New" class="btn btn-secondary"><i class="fas fa-plus"></i>New</a>
        <table id="dataTable" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Cover Photo</th>
                    <th>Title</th>
                    <th>Content</th>
                    <th>Character Content</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
    <tr>
        <td>
            @if (string.IsNullOrEmpty(item.CoverPhotoPath))
            {
<i class="no-image"></i> }
else
{
<img src="~/img/@item.CoverPhotoPath" alt="@item.Title" width="100" />}
        </td>
        <td>@item.Title</td>
        <td>@item.Content</td>
        <td>@item.CharacterContent</td>
        <td>@item.Time</td>
        <td>
            
            <form class="mb-2">
                <a class="btn btn-warning" asp-action="Edit"  asp-route-id="@item.Id">Edit</a>
                @*<input type="hidden" id="idEdit" value="@item.Id" name="idEdit" />*@
                @*<input class="btn btn-warning" type="submit" value="Edit" />*@
            </form>
            <form asp-action="Delete">
                <input type="hidden" id="id" value="@item.Id" name="id" />
                <input class="btn btn-danger" type="submit" value="Delete" />
            </form>
        </td>
    </tr>
}
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

GameInspectorWeb/Areas/Admin/Views/Events/New.cshtml
@model NewArticleViewModel
@{
    ViewData["Title"] = "New Article";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <div class="card card-primary">
            @*<div class="card-header">
                    <h3 class="card-title">Quick Example</h3>
                </div>*@
            <!-- /.card-header -->
            <!-- form start -->
            <form method="post" enctype="multipart/form-data">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Title">Article Title</label>
                        <input asp-for="Title" class="form-control" placeholder="Title" data-slugify-target="#Slug">
                        <span asp-validation-for="Title"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Content">Article Content</label>
                        <textarea asp-for="Content" class="form-control" rows="15" placeholder="Article Content"></textarea>
                        <span asp-validation-for="Content"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CharacterContent">Character Content</label>
                        <textarea class="form-control" asp-for="CharacterContent" rows="15" placeholder="Character Content"></textarea>
                        <span asp-validation-for="CharacterContent"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="VideoPath">Video Path</label>
                        <input class="form-control" asp-for="VideoPath" placeholder="Video Path URL">
                        <span asp-validation-for="VideoPath"></span>
                    </div>
                    <div class="form-group">
                        <select asp-for="SelectedCategories" asp-items="Model.Categories" multiple></select>
                        @*<span asp-validation-for="ArticleCategories"></span>*@
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">File input</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input asp-for="CoverPhoto" class="custom-file-input" id="exampleInputFile">
                                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                            </div>
                        </div>
                        <span asp-validation-for="CoverPhoto"></span>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFiles">Content Files input</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input asp-for="ContentPhotos" class="custom-file-input" id="exampleInputFiles" multiple>
                                <label class="custom-file-label" for="exampleInputFiles">Choose file</label>
                            </div>
                            @*<div class="input-group-append">
                    <span class="input-group-text">Upload</span>
                </div>*@
                        </div>
                        <span asp-validation-for="ContentPhotos"></span>
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.card -->

@section scripts {

    <partial name="_ValidationScriptsPartial" />

    <script>
        $('select').selectpicker();
        bsCustomFileInput.init();
    </script>

}